# EDA: beir_nq

In [1]:
import polars as pl
import os
import json

## Load Datasets

In [2]:
PATH_BEIR_NQ = "../data/beir_nq"
corpus_list = [json.loads(line) for line in open(os.path.join(PATH_BEIR_NQ, "corpus.jsonl"))]
queries_list = [json.loads(line) for line in open(os.path.join(PATH_BEIR_NQ, "queries.jsonl"))]
corpus = pl.DataFrame(corpus_list).with_row_index(name="idx").drop("metadata")
queries = pl.DataFrame(queries_list).with_row_index(name="idx").drop("metadata").rename({"text": "question"})

In [3]:
corpus.head()

shape: (5, 4)
┌─────┬──────┬───────────────────┬─────────────────────────────────┐
│ idx ┆ _id  ┆ title             ┆ text                            │
│ --- ┆ ---  ┆ ---               ┆ ---                             │
│ u32 ┆ str  ┆ str               ┆ str                             │
╞═════╪══════╪═══════════════════╪═════════════════════════════════╡
│ 0   ┆ doc0 ┆ Minority interest ┆ In accounting, minority intere… │
│ 1   ┆ doc1 ┆ Minority interest ┆ It is, however, possible (such… │
│ 2   ┆ doc2 ┆ Minority interest ┆ The reporting of 'minority int… │
│ 3   ┆ doc3 ┆ Minority interest ┆ Some investors have expressed … │
│ 4   ┆ doc4 ┆ Minority interest ┆ Minority interest is an integr… │
└─────┴──────┴───────────────────┴─────────────────────────────────┘

In [4]:
queries.head()

shape: (5, 3)
┌─────┬───────┬─────────────────────────────────┐
│ idx ┆ _id   ┆ question                        │
│ --- ┆ ---   ┆ ---                             │
│ u32 ┆ str   ┆ str                             │
╞═════╪═══════╪═════════════════════════════════╡
│ 0   ┆ test0 ┆ what is non controlling intere… │
│ 1   ┆ test1 ┆ how many episodes are in chica… │
│ 2   ┆ test2 ┆ who sings love will keep us al… │
│ 3   ┆ test3 ┆ who is the leader of the ontar… │
│ 4   ┆ test4 ┆ nitty gritty dirt band fishin … │
└─────┴───────┴─────────────────────────────────┘

## What are the sizes of the datasets?

In [5]:
len(corpus), len(queries)

(2681468, 3452)

## Saving processed dataframes

In [6]:
PROCESSED_PATH = "../data/beir_nq/processed"
os.makedirs(PROCESSED_PATH, exist_ok=True)
corpus.write_ipc(f"{PROCESSED_PATH}/corpus.feather", compression="zstd")
queries.write_ipc(f"{PROCESSED_PATH}/queries.feather", compression="zstd")

##